from aiohttp import web


async def get_indices_handler(request):
    """
    :param request: aiohttp request
    :return: aiohttp Response object
    """
    app = request.app

    response = {
        'data': [
         {
             "index": 's_8769380_1575980464585',
             "alias": 'products_8769380_sync',
             "section": 8769380,
             "publisher": 'Lands End',
             "name": 'USCD Production',
             "count": 129130,
             "tier": 1,
             "url": 'https://www.landsend.com/',
         },
            {
                "index": '1',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '2',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '3',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '4',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '5',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '6',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '7',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '8',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": '9',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": 's_8769380_1575980464585',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": 's_8769380_1575980464585',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": 's_8769380_1575980464585',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": 's_8769380_1575980464585',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": 's_8769380_1575980464585',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            },
            {
                "index": 's_8769380_1575980464585',
                "alias": 'products_8769380_sync',
                "section": 8769380,
                "publisher": 'Lands End',
                "name": 'USCD Production',
                "count": 129130,
                "tier": 1,
                "url": 'https://www.landsend.com/',
            }
        ],
        'page': 1,
        'total': 1
    }
    return web.json_response(response)
