name: Push to Master CI

on: 
  push:
    branches:
      - master

jobs:
  deploy-docker-image:
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@master
      - name: creates a build directory with a production build of the application
        run: |
          npm install
          npm run build
      - name: docker login
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile -t elasticsearch-metadata:$(date +%s)
