name: Push to Master CI

on: 
  push:
    branches:
      - master

jobs:
  build-react:
    runs-on: [ubuntu-18.04]
    steps:
      - name: creates a build directory with a production build of the application
        run: npm run build
  build-docker-image:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag elasticsearch-metadata:$(date +%s)
    needs: build-react
